#%RAML 1.0 NamedExample
value: 
  customerId: 100
  firstName: ram
  lastName: sharma
  phone: 1234567890
  address: kolkata
  idType: aadhar
  hotelId: 10
  hotelType: deluxe
  hotelCity: kerala
  hotelBookingId: 82
  bookingStartDate: 2021-08-22 
  bookingEndDate: 2021-08-26